#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationDegree.POL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="educationDegree")]
	public partial class EducationDegreeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertfieldInfo(fieldInfo instance);
    partial void UpdatefieldInfo(fieldInfo instance);
    partial void DeletefieldInfo(fieldInfo instance);
    partial void InsertuserInfo(userInfo instance);
    partial void UpdateuserInfo(userInfo instance);
    partial void DeleteuserInfo(userInfo instance);
    partial void InsertgradeInfo(gradeInfo instance);
    partial void UpdategradeInfo(gradeInfo instance);
    partial void DeletegradeInfo(gradeInfo instance);
    partial void InsertpostFieldInfo(postFieldInfo instance);
    partial void UpdatepostFieldInfo(postFieldInfo instance);
    partial void DeletepostFieldInfo(postFieldInfo instance);
    partial void InsertpostInfo(postInfo instance);
    partial void UpdatepostInfo(postInfo instance);
    partial void DeletepostInfo(postInfo instance);
    partial void InserttendencyInfo(tendencyInfo instance);
    partial void UpdatetendencyInfo(tendencyInfo instance);
    partial void DeletetendencyInfo(tendencyInfo instance);
    #endregion
		
		
		public EducationDegreeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EducationDegreeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EducationDegreeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EducationDegreeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<fieldInfo> fieldInfos
		{
			get
			{
				return this.GetTable<fieldInfo>();
			}
		}
		
		public System.Data.Linq.Table<userInfo> userInfos
		{
			get
			{
				return this.GetTable<userInfo>();
			}
		}
		
		public System.Data.Linq.Table<gradeInfo> gradeInfos
		{
			get
			{
				return this.GetTable<gradeInfo>();
			}
		}
		
		public System.Data.Linq.Table<postFieldInfo> postFieldInfos
		{
			get
			{
				return this.GetTable<postFieldInfo>();
			}
		}
		
		public System.Data.Linq.Table<postInfo> postInfos
		{
			get
			{
				return this.GetTable<postInfo>();
			}
		}
		
		public System.Data.Linq.Table<tendencyInfo> tendencyInfos
		{
			get
			{
				return this.GetTable<tendencyInfo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.fieldInfo")]
	public partial class fieldInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _fieldCode;
		
		private string _fieldName;
		
		private string _dateInsert;
		
		private System.Nullable<bool> _deleted;
		
		private EntitySet<postFieldInfo> _postFieldInfos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfieldCodeChanging(int value);
    partial void OnfieldCodeChanged();
    partial void OnfieldNameChanging(string value);
    partial void OnfieldNameChanged();
    partial void OndateInsertChanging(string value);
    partial void OndateInsertChanged();
    partial void OndeletedChanging(System.Nullable<bool> value);
    partial void OndeletedChanged();
    #endregion
		
		public fieldInfo()
		{
			this._postFieldInfos = new EntitySet<postFieldInfo>(new Action<postFieldInfo>(this.attach_postFieldInfos), new Action<postFieldInfo>(this.detach_postFieldInfos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fieldCode", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int fieldCode
		{
			get
			{
				return this._fieldCode;
			}
			set
			{
				if ((this._fieldCode != value))
				{
					this.OnfieldCodeChanging(value);
					this.SendPropertyChanging();
					this._fieldCode = value;
					this.SendPropertyChanged("fieldCode");
					this.OnfieldCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fieldName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string fieldName
		{
			get
			{
				return this._fieldName;
			}
			set
			{
				if ((this._fieldName != value))
				{
					this.OnfieldNameChanging(value);
					this.SendPropertyChanging();
					this._fieldName = value;
					this.SendPropertyChanged("fieldName");
					this.OnfieldNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateInsert", DbType="NChar(10)")]
		public string dateInsert
		{
			get
			{
				return this._dateInsert;
			}
			set
			{
				if ((this._dateInsert != value))
				{
					this.OndateInsertChanging(value);
					this.SendPropertyChanging();
					this._dateInsert = value;
					this.SendPropertyChanged("dateInsert");
					this.OndateInsertChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="Bit")]
		public System.Nullable<bool> deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="fieldInfo_postFieldInfo", Storage="_postFieldInfos", ThisKey="fieldCode", OtherKey="fieldCode")]
		public EntitySet<postFieldInfo> postFieldInfos
		{
			get
			{
				return this._postFieldInfos;
			}
			set
			{
				this._postFieldInfos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_postFieldInfos(postFieldInfo entity)
		{
			this.SendPropertyChanging();
			entity.fieldInfo = this;
		}
		
		private void detach_postFieldInfos(postFieldInfo entity)
		{
			this.SendPropertyChanging();
			entity.fieldInfo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.userInfo")]
	public partial class userInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _userCode;
		
		private string _fName;
		
		private string _lName;
		
		private string _userName;
		
		private string _pass;
		
		private System.Nullable<bool> _deleted;
		
		private string _email;
		
		private string _mobile;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserCodeChanging(int value);
    partial void OnuserCodeChanged();
    partial void OnfNameChanging(string value);
    partial void OnfNameChanged();
    partial void OnlNameChanging(string value);
    partial void OnlNameChanged();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnpassChanging(string value);
    partial void OnpassChanged();
    partial void OndeletedChanging(System.Nullable<bool> value);
    partial void OndeletedChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnmobileChanging(string value);
    partial void OnmobileChanged();
    #endregion
		
		public userInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userCode", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int userCode
		{
			get
			{
				return this._userCode;
			}
			set
			{
				if ((this._userCode != value))
				{
					this.OnuserCodeChanging(value);
					this.SendPropertyChanging();
					this._userCode = value;
					this.SendPropertyChanged("userCode");
					this.OnuserCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string fName
		{
			get
			{
				return this._fName;
			}
			set
			{
				if ((this._fName != value))
				{
					this.OnfNameChanging(value);
					this.SendPropertyChanging();
					this._fName = value;
					this.SendPropertyChanged("fName");
					this.OnfNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lName", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string lName
		{
			get
			{
				return this._lName;
			}
			set
			{
				if ((this._lName != value))
				{
					this.OnlNameChanging(value);
					this.SendPropertyChanging();
					this._lName = value;
					this.SendPropertyChanged("lName");
					this.OnlNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userName", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					this.OnuserNameChanging(value);
					this.SendPropertyChanging();
					this._userName = value;
					this.SendPropertyChanged("userName");
					this.OnuserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string pass
		{
			get
			{
				return this._pass;
			}
			set
			{
				if ((this._pass != value))
				{
					this.OnpassChanging(value);
					this.SendPropertyChanging();
					this._pass = value;
					this.SendPropertyChanged("pass");
					this.OnpassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="Bit")]
		public System.Nullable<bool> deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile", DbType="Char(11)")]
		public string mobile
		{
			get
			{
				return this._mobile;
			}
			set
			{
				if ((this._mobile != value))
				{
					this.OnmobileChanging(value);
					this.SendPropertyChanging();
					this._mobile = value;
					this.SendPropertyChanged("mobile");
					this.OnmobileChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.gradeInfo")]
	public partial class gradeInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _gradeCode;
		
		private string _gradeName;
		
		private System.Nullable<bool> _deleted;
		
		private string _description;
		
		private EntitySet<postFieldInfo> _postFieldInfos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OngradeCodeChanging(int value);
    partial void OngradeCodeChanged();
    partial void OngradeNameChanging(string value);
    partial void OngradeNameChanged();
    partial void OndeletedChanging(System.Nullable<bool> value);
    partial void OndeletedChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    #endregion
		
		public gradeInfo()
		{
			this._postFieldInfos = new EntitySet<postFieldInfo>(new Action<postFieldInfo>(this.attach_postFieldInfos), new Action<postFieldInfo>(this.detach_postFieldInfos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gradeCode", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int gradeCode
		{
			get
			{
				return this._gradeCode;
			}
			set
			{
				if ((this._gradeCode != value))
				{
					this.OngradeCodeChanging(value);
					this.SendPropertyChanging();
					this._gradeCode = value;
					this.SendPropertyChanged("gradeCode");
					this.OngradeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gradeName", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string gradeName
		{
			get
			{
				return this._gradeName;
			}
			set
			{
				if ((this._gradeName != value))
				{
					this.OngradeNameChanging(value);
					this.SendPropertyChanging();
					this._gradeName = value;
					this.SendPropertyChanged("gradeName");
					this.OngradeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="Bit")]
		public System.Nullable<bool> deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(100)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="gradeInfo_postFieldInfo", Storage="_postFieldInfos", ThisKey="gradeCode", OtherKey="gradeCode")]
		public EntitySet<postFieldInfo> postFieldInfos
		{
			get
			{
				return this._postFieldInfos;
			}
			set
			{
				this._postFieldInfos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_postFieldInfos(postFieldInfo entity)
		{
			this.SendPropertyChanging();
			entity.gradeInfo = this;
		}
		
		private void detach_postFieldInfos(postFieldInfo entity)
		{
			this.SendPropertyChanging();
			entity.gradeInfo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.postFieldInfo")]
	public partial class postFieldInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _postFieldCode;
		
		private int _postCode;
		
		private int _fieldCode;
		
		private int _tendencyCode;
		
		private int _gradeCode;
		
		private string _dataInsert;
		
		private System.Nullable<bool> _deleted;
		
		private string _description;
		
		private EntityRef<fieldInfo> _fieldInfo;
		
		private EntityRef<gradeInfo> _gradeInfo;
		
		private EntityRef<postInfo> _postInfo;
		
		private EntityRef<tendencyInfo> _tendencyInfo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpostFieldCodeChanging(int value);
    partial void OnpostFieldCodeChanged();
    partial void OnpostCodeChanging(int value);
    partial void OnpostCodeChanged();
    partial void OnfieldCodeChanging(int value);
    partial void OnfieldCodeChanged();
    partial void OntendencyCodeChanging(int value);
    partial void OntendencyCodeChanged();
    partial void OngradeCodeChanging(int value);
    partial void OngradeCodeChanged();
    partial void OndataInsertChanging(string value);
    partial void OndataInsertChanged();
    partial void OndeletedChanging(System.Nullable<bool> value);
    partial void OndeletedChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    #endregion
		
		public postFieldInfo()
		{
			this._fieldInfo = default(EntityRef<fieldInfo>);
			this._gradeInfo = default(EntityRef<gradeInfo>);
			this._postInfo = default(EntityRef<postInfo>);
			this._tendencyInfo = default(EntityRef<tendencyInfo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postFieldCode", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int postFieldCode
		{
			get
			{
				return this._postFieldCode;
			}
			set
			{
				if ((this._postFieldCode != value))
				{
					this.OnpostFieldCodeChanging(value);
					this.SendPropertyChanging();
					this._postFieldCode = value;
					this.SendPropertyChanged("postFieldCode");
					this.OnpostFieldCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postCode", DbType="Int NOT NULL")]
		public int postCode
		{
			get
			{
				return this._postCode;
			}
			set
			{
				if ((this._postCode != value))
				{
					if (this._postInfo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnpostCodeChanging(value);
					this.SendPropertyChanging();
					this._postCode = value;
					this.SendPropertyChanged("postCode");
					this.OnpostCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fieldCode", DbType="Int NOT NULL")]
		public int fieldCode
		{
			get
			{
				return this._fieldCode;
			}
			set
			{
				if ((this._fieldCode != value))
				{
					if (this._fieldInfo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfieldCodeChanging(value);
					this.SendPropertyChanging();
					this._fieldCode = value;
					this.SendPropertyChanged("fieldCode");
					this.OnfieldCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tendencyCode", DbType="Int NOT NULL")]
		public int tendencyCode
		{
			get
			{
				return this._tendencyCode;
			}
			set
			{
				if ((this._tendencyCode != value))
				{
					if (this._tendencyInfo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntendencyCodeChanging(value);
					this.SendPropertyChanging();
					this._tendencyCode = value;
					this.SendPropertyChanged("tendencyCode");
					this.OntendencyCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gradeCode", DbType="Int NOT NULL")]
		public int gradeCode
		{
			get
			{
				return this._gradeCode;
			}
			set
			{
				if ((this._gradeCode != value))
				{
					if (this._gradeInfo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OngradeCodeChanging(value);
					this.SendPropertyChanging();
					this._gradeCode = value;
					this.SendPropertyChanged("gradeCode");
					this.OngradeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataInsert", DbType="NChar(10)")]
		public string dataInsert
		{
			get
			{
				return this._dataInsert;
			}
			set
			{
				if ((this._dataInsert != value))
				{
					this.OndataInsertChanging(value);
					this.SendPropertyChanging();
					this._dataInsert = value;
					this.SendPropertyChanged("dataInsert");
					this.OndataInsertChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="Bit")]
		public System.Nullable<bool> deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(MAX)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="fieldInfo_postFieldInfo", Storage="_fieldInfo", ThisKey="fieldCode", OtherKey="fieldCode", IsForeignKey=true)]
		public fieldInfo fieldInfo
		{
			get
			{
				return this._fieldInfo.Entity;
			}
			set
			{
				fieldInfo previousValue = this._fieldInfo.Entity;
				if (((previousValue != value) 
							|| (this._fieldInfo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._fieldInfo.Entity = null;
						previousValue.postFieldInfos.Remove(this);
					}
					this._fieldInfo.Entity = value;
					if ((value != null))
					{
						value.postFieldInfos.Add(this);
						this._fieldCode = value.fieldCode;
					}
					else
					{
						this._fieldCode = default(int);
					}
					this.SendPropertyChanged("fieldInfo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="gradeInfo_postFieldInfo", Storage="_gradeInfo", ThisKey="gradeCode", OtherKey="gradeCode", IsForeignKey=true)]
		public gradeInfo gradeInfo
		{
			get
			{
				return this._gradeInfo.Entity;
			}
			set
			{
				gradeInfo previousValue = this._gradeInfo.Entity;
				if (((previousValue != value) 
							|| (this._gradeInfo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._gradeInfo.Entity = null;
						previousValue.postFieldInfos.Remove(this);
					}
					this._gradeInfo.Entity = value;
					if ((value != null))
					{
						value.postFieldInfos.Add(this);
						this._gradeCode = value.gradeCode;
					}
					else
					{
						this._gradeCode = default(int);
					}
					this.SendPropertyChanged("gradeInfo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="postInfo_postFieldInfo", Storage="_postInfo", ThisKey="postCode", OtherKey="postCode", IsForeignKey=true)]
		public postInfo postInfo
		{
			get
			{
				return this._postInfo.Entity;
			}
			set
			{
				postInfo previousValue = this._postInfo.Entity;
				if (((previousValue != value) 
							|| (this._postInfo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._postInfo.Entity = null;
						previousValue.postFieldInfos.Remove(this);
					}
					this._postInfo.Entity = value;
					if ((value != null))
					{
						value.postFieldInfos.Add(this);
						this._postCode = value.postCode;
					}
					else
					{
						this._postCode = default(int);
					}
					this.SendPropertyChanged("postInfo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tendencyInfo_postFieldInfo", Storage="_tendencyInfo", ThisKey="tendencyCode", OtherKey="tendencyCode", IsForeignKey=true)]
		public tendencyInfo tendencyInfo
		{
			get
			{
				return this._tendencyInfo.Entity;
			}
			set
			{
				tendencyInfo previousValue = this._tendencyInfo.Entity;
				if (((previousValue != value) 
							|| (this._tendencyInfo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tendencyInfo.Entity = null;
						previousValue.postFieldInfos.Remove(this);
					}
					this._tendencyInfo.Entity = value;
					if ((value != null))
					{
						value.postFieldInfos.Add(this);
						this._tendencyCode = value.tendencyCode;
					}
					else
					{
						this._tendencyCode = default(int);
					}
					this.SendPropertyChanged("tendencyInfo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.postInfo")]
	public partial class postInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _postCode;
		
		private string _postName;
		
		private string _raster;
		
		private string _dateInsert;
		
		private string _description;
		
		private System.Nullable<bool> _deleted;
		
		private EntitySet<postFieldInfo> _postFieldInfos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpostCodeChanging(int value);
    partial void OnpostCodeChanged();
    partial void OnpostNameChanging(string value);
    partial void OnpostNameChanged();
    partial void OnrasterChanging(string value);
    partial void OnrasterChanged();
    partial void OndateInsertChanging(string value);
    partial void OndateInsertChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OndeletedChanging(System.Nullable<bool> value);
    partial void OndeletedChanged();
    #endregion
		
		public postInfo()
		{
			this._postFieldInfos = new EntitySet<postFieldInfo>(new Action<postFieldInfo>(this.attach_postFieldInfos), new Action<postFieldInfo>(this.detach_postFieldInfos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postCode", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int postCode
		{
			get
			{
				return this._postCode;
			}
			set
			{
				if ((this._postCode != value))
				{
					this.OnpostCodeChanging(value);
					this.SendPropertyChanging();
					this._postCode = value;
					this.SendPropertyChanged("postCode");
					this.OnpostCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string postName
		{
			get
			{
				return this._postName;
			}
			set
			{
				if ((this._postName != value))
				{
					this.OnpostNameChanging(value);
					this.SendPropertyChanging();
					this._postName = value;
					this.SendPropertyChanged("postName");
					this.OnpostNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_raster", DbType="NVarChar(40)")]
		public string raster
		{
			get
			{
				return this._raster;
			}
			set
			{
				if ((this._raster != value))
				{
					this.OnrasterChanging(value);
					this.SendPropertyChanging();
					this._raster = value;
					this.SendPropertyChanged("raster");
					this.OnrasterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateInsert", DbType="NChar(10)")]
		public string dateInsert
		{
			get
			{
				return this._dateInsert;
			}
			set
			{
				if ((this._dateInsert != value))
				{
					this.OndateInsertChanging(value);
					this.SendPropertyChanging();
					this._dateInsert = value;
					this.SendPropertyChanged("dateInsert");
					this.OndateInsertChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(MAX)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="Bit")]
		public System.Nullable<bool> deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="postInfo_postFieldInfo", Storage="_postFieldInfos", ThisKey="postCode", OtherKey="postCode")]
		public EntitySet<postFieldInfo> postFieldInfos
		{
			get
			{
				return this._postFieldInfos;
			}
			set
			{
				this._postFieldInfos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_postFieldInfos(postFieldInfo entity)
		{
			this.SendPropertyChanging();
			entity.postInfo = this;
		}
		
		private void detach_postFieldInfos(postFieldInfo entity)
		{
			this.SendPropertyChanging();
			entity.postInfo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tendencyInfo")]
	public partial class tendencyInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tendencyCode;
		
		private string _tendencyName;
		
		private int _fieldCode;
		
		private System.Nullable<bool> _deleted;
		
		private EntitySet<postFieldInfo> _postFieldInfos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntendencyCodeChanging(int value);
    partial void OntendencyCodeChanged();
    partial void OntendencyNameChanging(string value);
    partial void OntendencyNameChanged();
    partial void OnfieldCodeChanging(int value);
    partial void OnfieldCodeChanged();
    partial void OndeletedChanging(System.Nullable<bool> value);
    partial void OndeletedChanged();
    #endregion
		
		public tendencyInfo()
		{
			this._postFieldInfos = new EntitySet<postFieldInfo>(new Action<postFieldInfo>(this.attach_postFieldInfos), new Action<postFieldInfo>(this.detach_postFieldInfos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tendencyCode", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tendencyCode
		{
			get
			{
				return this._tendencyCode;
			}
			set
			{
				if ((this._tendencyCode != value))
				{
					this.OntendencyCodeChanging(value);
					this.SendPropertyChanging();
					this._tendencyCode = value;
					this.SendPropertyChanged("tendencyCode");
					this.OntendencyCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tendencyName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tendencyName
		{
			get
			{
				return this._tendencyName;
			}
			set
			{
				if ((this._tendencyName != value))
				{
					this.OntendencyNameChanging(value);
					this.SendPropertyChanging();
					this._tendencyName = value;
					this.SendPropertyChanged("tendencyName");
					this.OntendencyNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fieldCode", DbType="Int NOT NULL")]
		public int fieldCode
		{
			get
			{
				return this._fieldCode;
			}
			set
			{
				if ((this._fieldCode != value))
				{
					this.OnfieldCodeChanging(value);
					this.SendPropertyChanging();
					this._fieldCode = value;
					this.SendPropertyChanged("fieldCode");
					this.OnfieldCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="Bit")]
		public System.Nullable<bool> deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tendencyInfo_postFieldInfo", Storage="_postFieldInfos", ThisKey="tendencyCode", OtherKey="tendencyCode")]
		public EntitySet<postFieldInfo> postFieldInfos
		{
			get
			{
				return this._postFieldInfos;
			}
			set
			{
				this._postFieldInfos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_postFieldInfos(postFieldInfo entity)
		{
			this.SendPropertyChanging();
			entity.tendencyInfo = this;
		}
		
		private void detach_postFieldInfos(postFieldInfo entity)
		{
			this.SendPropertyChanging();
			entity.tendencyInfo = null;
		}
	}
}
#pragma warning restore 1591
